---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ttfm.fullname" . }}-agent
  labels:
    {{- include "ttfm.labels" . | nindent 4 }}
data:
  config.yaml: |
    controller:
      listen_address: {{ include "ttfm.fullname" . }}-controller.{{ .Release.Namespace }}.svc.cluster.local:50052
