apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ttfm.fullname" . }}
  labels:
    {{- include "ttfm.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
automountServiceAccountToken: true
